### ISSUE TITLE
Readme: Advice on how to implement a git filter

### ISSUE THREAD

**Issue by blaggacao** [ryantm/agenix#11]
DRY &rarr; https://github.com/nrdxp/nixflk/issues/37

So that a similar functionality to `git crypt` can be achieved.

**Comment by blaggacao** [comment]
I guess the added value would lie in the metadata of `./secrets.nix`. Some sort of `clean` & `smudge`,evtl. `diff` function [here](https://github.com/ryantm/agenix/blob/85fd85e31854182373fd3582a293462a1b3cf82d/pkgs/agenix.nix#L97)?

**Comment by ryantm** [comment]
As I said in #14 I don't think a git filter makes sense because we want the secrets encrypted at rest.
