### ISSUE TITLE
Nextcloud becomes inaccessible whenever secrets are deployed

### ISSUE THREAD

**Issue by wyndon** [ryantm/agenix#112]
This happens even when Nextcloud doesn't need to restart. Restarting Nextcloud manually solves the problem, but it happens every time secrets are deployed. Gitea, on the other hand, does not have this problem. Any solution ?

![image](https://user-images.githubusercontent.com/72203260/165552790-22ad16ab-ed19-4884-b8a5-432b168fe1d0.png)

**Comment by ryantm** [comment]
Eventually we want to support indicating which services need to be restarted. For now, you can use this new feature of NixOS yourself in your own activation script: https://github.com/ryantm/agenix/issues/84#issuecomment-1099884559
