### ISSUE TITLE
identityPaths doesn't act like list

### ISSUE THREAD

**Issue by gergovari** [ryantm/agenix#116]
Setting `age.identityPaths = [ "/etc/ssh/ssh_host_rsa_key" "/etc/nixos/keys/${config.networking.hostName}/id_rsa" ];` will give a warning that the first doesn't exist (at the moment, after boot it will) and I expected it to fallback  to the second one. That doesn't happen and it fails to decrypt the secrets. Switching the order works but then if workaround path doesn't exist the same issue comes up.

**Comment by ryantm** [comment]
Needs https://github.com/str4d/rage/issues/294 to be fixed.

**Comment by n8henrie** [comment]
@ryantm reviewing that issue, seems like this is more of a decision on the part of the rage team than something that wil be fixed.

Might there be a way to filter `identities` for paths that exist? https://github.com/ryantm/agenix/blob/b7ffcfe77f817d9ee992640ba1f270718d197f28/modules/age.nix#L57  If so, it would be a nice improvement to the user experience (and perhaps ameliorate some issues with https://github.com/ryantm/agenix/issues/45).

Happy to work on PR if you think this slight departure from `rage` behavior would be acceptable.

Perhaps could even have a user-facing flag that defaults to `false`: `ignoreMissingIdentities`?

**Comment by ryantm** [comment]
I think you're right. Let's work around it. I don't think we need an option!

**Comment by cole-h** [comment]
If you weren't already planning on it, I'd strongly suggest implementing the check as part of one of the scripts, rather than in Nix; paths may not be available at build / evaluation time, but may when the script runs.
