### ISSUE TITLE
Order of operations

### ISSUE THREAD

**Issue by jsimonetti** [ryantm/agenix#117]
As suggested in Matrix I am creating this issue about the order in which agenix operates.

When switching generations I consistantly see the following order of operations in the log output:
```
[agenix] symlinking new secrets to /run/agenix (generation 6)...
[agenix] removing old secrets (generation 5)...
[agenix] decrypting root secrets...
decrypting '/nix/store/xxx.age' to '/run/agenix.d/6/xxx'...
decrypting '/nix/store/yyy.age' to '/run/agenix.d/6/yyy'...
[agenix] decrypting non-root secrets...
decrypting '/nix/store/zzz.age' to '/run/agenix.d/6/zzz'...
```

This got me wondering as I would expect the order of operations to be:
1) decrypt secrets into new generation
2) symlink new secrets
3) remove old generation/secrets

Could we get some clarification about the actual order?

**Comment by ryantm** [comment]
@cole-h as the author of the symlinking PR, maybe you can comment?

**Comment by cole-h** [comment]
Yeah, that sounds like a good change to make -- thanks for catching that!
