### ISSUE TITLE
Encrypt `networking.hostFiles`

### ISSUE THREAD

**Issue by timhae** [ryantm/agenix#121]
Thanks for your great tool! I tried to encrpyt `networking.hostFiles` with agenix but a rebuild fails with
```
error: builder for '/nix/store/8f45i9pw24b69z4kf1vyhqcj6glad3nm-hosts.drv' failed with exit code 1;
       last 1 log lines:
       > cat: /run/agenix/hosts: No such file or directory
```
which is to expect I assume since the rebuild expects this file to be in place before the agenix secrets are created/encrypted. Is there any way I could mage this work?

**Comment by ryantm** [comment]
Please include the relevant NixOS configuration that generates this error.

**Comment by timhae** [comment]
Thanks for getting back so quickly. Sure, here is my config:
```
{ config, lib, pkgs, agenix, ...}: {
  age.secrets = {
    hosts.file = ../secrets/hosts.age'
    adminPW.file = ../secrets/adminPW.age;
  };
  networking.hostFiles = [ config.age.secrets.hosts.path ];
  users.users.root = {
    isSystemUser = true;
    passwordFile = config.age.secrets.adminPW.path;
  };
}
```
and `secrets.nix`:
```
let
  laptop1 = builtins.readFile ./laptop1.pub;
  desktop1 = builtins.readFile ./desktop1.pub;
  server = builtins.readFile ./server.pub;
  all = [ laptop1 desktop1 server ];
in {
  "adminPW.age".publicKeys = all;
  "hosts.age".publi cKeys = all;
}
```
Setting the admin password works, hosts file not. Please let me know if there is anything else I can do.
The [options](https://search.nixos.org/options?channel=22.05&show=networking.hostFiles&from=0&size=50&sort=relevance&type=packages&query=networking.host) suggest, that `hostFiles` should be a list of path, in the example they give a list of string, I tried both options to no avail.

**Comment by danielphan2003** [comment]
This is because NixOS cannot access `/run` while *building* a file that symlink to `/etc/hosts`. It is isolated from the rest of the file system so your best bet is to find a way to run `cat /run/agenix/hosts >> /etc/hosts` every time NixOS boots.

See also https://github.com/NixOS/nixpkgs/blob/5a0e0d73b944157328d54c4ded1cf2f0146a86a5/nixos/modules/config/networking.nix#L199 and https://github.com/NixOS/nixpkgs/blob/f7bb0cf1042b8565f4d8881fa2da2cedc15a979b/pkgs/build-support/trivial-builders.nix#L358

**Comment by timhae** [comment]
Thanks for the pointer, will take a look at that.

**Comment by pathob** [comment]
@timhae Did you find a solution for it? Piping into `/etc/hosts` does not work as suggested.

What works is `environment.etc.hosts.source = lib.mkForce config.age.secrets.hosts.path;` but then all other hosts-related config becomes void...

**Comment by timhae** [comment]
I don't remember, sorry. You could probably also do this as part of an activation script
