### ISSUE TITLE
Feature: encrypt whole file

### ISSUE THREAD

**Issue by bobbbay** [ryantm/agenix#122]
I have a huge file (a few MBs) that I want to encrypt with agenix. I can't simply copy/paste the file - it's too big, and it's in another format, too. I want to be able to simply run `agenix --from-file <secret.age> <original.filetype>`.

**Comment by cole-h** [comment]
There are a few workarounds you could try in this issue: https://github.com/ryantm/agenix/issues/33.

**Comment by bobbbay** [comment]
I ended up using `-e`, copying the file while Nano was open, and closing Nano once complete. It seems like ragenix has the right solution, though. Thank you, #33 probably takes precedence over this issue.
