### ISSUE TITLE
secret readable by multiple service

### ISSUE THREAD

**Issue by happysalada** [ryantm/agenix#128]
Just want to add a question, the only way to have a secret readable by multiple service is to use the `group` attribute right ?
That would mean that services run with DynamicUser won't be able to read a secret, correct ?

**Comment by samhza** [comment]
You can use `LoadCredential` in `serviceConfig` to pass a secret to a service. This works with services with `DynamicUser` enabled. Example:
```nix
{
      LoadCredential = "config.ini:${config.age.secrets."some-service-config.ini".path}";
      ExecStart = "some-service --config %d/config.ini";
}
```

More info is available in the [Credentials section](https://www.freedesktop.org/software/systemd/man/systemd.exec.html#Credentials) of the systemd.exec docs.

**Comment by happysalada** [comment]
That is actually exactly what I was looking for, thank you!
