### ISSUE TITLE
Age attribute not found

### ISSUE THREAD

**Issue by morphykuffour** [ryantm/agenix#129]
I am new to nixos and I am currently trying to encrypt my tailscale secret key with rage and use agenix to unencrypt at runtime. I have been able to encrypt the secret key with rage and I have placed the age file in my secrets directory

```bash
rage -R ~/.ssh/id_ed25519.pub tailscale.xps17-nixos.txt > ts-xps17-nixos.age
```

I can unencrypt and view the secret key with agenix using the following,
```bash
agenix -e ts-xps17-nixos.age
```
The following is my secrets.nix file
![image](https://user-images.githubusercontent.com/23323356/203630613-c0817e26-5cab-4c22-afb8-a30e21f540d5.png)

However I am getting this error when I try to build and switch to my latest configuration
```
. error: attribute 'ts-xps17-nixos' missing
```
![image](https://user-images.githubusercontent.com/23323356/203629635-3d7a2e8a-c359-41d0-a15f-2a2adb4b59b7.png)

**Comment by cole-h** [comment]
You are missing some configuration. Now that you've setup your `secrets.nix`, you'll also need to add those secrets to a NixOS module. There is an example on how to do that in the README, under the [Tutorial](https://github.com/ryantm/agenix#tutorial) section: https://github.com/ryantm/agenix/blob/a630400067c6d03c9b3e0455347dc8559db14288/README.md?plain=1#L227

**Comment by morphykuffour** [comment]
I have added the age encrypted file but I still cannot build because I am getting an error
![image](https://user-images.githubusercontent.com/23323356/203784204-5eea97d4-2108-4c1e-9c21-10fba80f1266.png)
  
This is the erorr:
![image](https://user-images.githubusercontent.com/23323356/203784343-6edee3c9-0159-4176-bd57-3a239a81d6d8.png)

I do not think I have to do this but should I import secrets.nix file into my nixos module?

**Comment by ryantm** [comment]
I think you may have one too many ../ in your config line. Double check the path is correct and that the encrypted file is checked into the git repo if you're using one. You definitely should've import the secrets.nix file. It is only for the agenix tool to use.

**Comment by morphykuffour** [comment]
Oh I see so the age files have to be in the git repo. That was my mistake. I am now getting a new error when building. Is this not related to the issue I initially opened. Here is the error:
![image](https://user-images.githubusercontent.com/23323356/203799999-5bf4308e-edd2-443a-b08a-5a5598770d00.png)

**Comment by ryantm** [comment]
It looks like you used a private key that is in a home directory. Agenix only looks in the /etc/ssh directory. If you want it to use a different path, you need to set `age.identityPaths` to something else. https://github.com/ryantm/agenix/#ageidentitypaths

**Comment by morphykuffour** [comment]
Thank you so much I was able to get it to work. I appreciate all your work and this piece of software is truly magically. Happy holidays.
