### ISSUE TITLE
Is lib.fileContents an anti-pattern?

### ISSUE THREAD

**Issue by agentx3** [ryantm/agenix#135]
Been trying to implement agenix into the deployment of a steam game server, where the server password is passed as an arg in the command-line.

Played around a bunch trying to get a way for it to work, avoiding `builtins.readFile`. Landed on something like this in my systemd service config. This is how I'm using it. Just wanted to know if this was secure, to the best of your knowledge?
```
serviceConfig = {
   ExecStart = lib.escapeShellArgs [
     "/var/lib/steam-app-${steam-app}/valheim_server.x86_64"
     "-nographics"
     "-batchmode"
     "-savedir" "/var/lib/valheim/save"
     "-name" "YOUR SERVER NAME"
     "-port" "2456"
     "-world" "Dedicated"
     "-password" "${lib.fileContents config.age.secrets.valheim_password.path}" 
     "-public" "0"
     "-backups" "0"
   ]; 
  ...
};     
```

**Comment by cole-h** [comment]
`lib.fileContents` is implemented with `builtins.readFile`, so the only difference is that you don't get a trailing newline (if the file had one to begin with): https://github.com/NixOS/nixpkgs/blob/4f10ebbd5c89c4e623e81101d5d83e3c49b978c1/lib/strings.nix#L986

So, I think the answer to your question is: yes, `lib.fileContents` is an antipattern.

Something more secure would be to pass it in as an environment variable. If you 1) give the service `SupplementalGroups = [ "keys" ];`; and 2) make the `ExecStart` an actual script, you should be able to do something like `export VALHEIM_PASSWORD=$(cat ${config.age.secrets.valheim_password.path})` and refer to that env var for `-password`. (I think you can skip the `SupplementalGroups` part if you change the user of the secret file to the user of the service and put the file somewhere only that unit can read from; this won't work with DynamicUser, though.)
