### ISSUE TITLE
agenix-pass a pass compliant

### ISSUE THREAD

**Issue by blaggacao** [ryantm/agenix#15]
For a more unified, devops-dream, future-proof secrets management.

https://github.com/nrdxp/nixflk/issues/56

There is the advent of (cheap, as in here-implementation / here-maintenance) FIDO2 integration on the horizon: https://github.com/str4d/age-plugin-yubikey &mdash; specifically: https://github.com/str4d/age-plugin-yubikey/pull/1

**Comment by ryantm** [comment]
I don't understand what this is asking for @blaggacao. It seems to be talking about yubikey and pass. What do you want to store in pass?

**Comment by blaggacao** [comment]
As far as I can remember, this was part of a research stride. 

This has been driven by a vision to manage pass secrets as part of the nixos host (or home) state via age (instead of gpg). Agenix, in that idea, would provide the api and implementation of how secrets would be stored.

The specific link represents a relatively cheap way to unlock any age encrypted secret with a FIDO2 device: an enabler for any age-pass

Since then, there seems to be a specification coming around: https://hackmd.io/@str4d/age-plugin-yubikey

To this end, I'd guess this issue asked for acknowledgment of age-plugin-yubikey, and a general feedback on the (abstract) idea of an agenix-pass. (If that makes sense)

**Comment by asymmetric** [comment]
There's [preliminary support](https://github.com/str4d/rage/releases/tag/v0.6.0) for rage plugins, [one of which](https://github.com/str4d/age-plugin-yubikey) is for Yubikeys. Until that lands more properly, I don't think there's much to do on agenix's side though.

**Comment by blaggacao** [comment]
Should we close this? This is not going to be immediatly actionable. I think we are still a few upstream iterations away for crafting well-integrated nixos specific solutions for `pass`' state.

**Comment by blaggacao** [comment]
For what it's worth, word is spreading that the state of the age ecosystem might slowly have reached a state where this can be attempted upon.

**Comment by pinpox** [comment]
Any updates on the yubikey support?
