### ISSUE TITLE
agenix complains about unsupported key ~/.ssh/id_rsa⁩, even if -i is used

### ISSUE THREAD

**Issue by nomeata** [ryantm/agenix#151]
I have an old `~/.ssh/id_rsa⁩` and a newer `~/.ssh/id_ed25519` that I mostly use. `agenix` picks the former by default and complains about it being old, which is fine. But I’d expect that if I pass `-i` explicitly, it will not look at the other file, but it does:
```
…/secrets $ agenix -e nullmailer.age -i ~/.ssh/id_ed25519 
Error: Unsupported SSH key: ⁨/home/jojo/.ssh/id_rsa⁩

Insecure Encrypted Key Format
-----------------------------
Prior to OpenSSH version 7.8, if a password was set when generating a new
DSA, ECDSA, or RSA key, ssh-keygen would encrypt the key using the encrypted
PEM format. This encryption format is insecure and should no longer be used.

You can migrate your key to the encrypted SSH private key format (which has
been supported by OpenSSH since version 6.5, released in January 2014) by
changing its passphrase with the following command:

    ⁨ssh-keygen -o -p⁩

If you are using an OpenSSH version between 6.5 and 7.7 (such as the default
OpenSSH provided on Ubuntu 18.04 LTS), you can use the following command to
force keys to be generated using the new format:

    ⁨ssh-keygen -o⁩


[ Did rage not do what you expected? Could an error be more useful? ]
[ Tell us: https://str4d.xyz/rage/report                            ]
```

I can work-around it by temporarily moving `~/.ssh/id_rsa⁩` out of the way.

**Comment by n8henrie** [comment]
Thanks for the issue.

To clarify, does the operation succeed when you specify `-i` and it's just the warning that you're concerned about?

**Comment by nomeata** [comment]
No, it fails with that error message (but succeeds if I rename the bad key)

**Comment by ryantm** [comment]
I'm going to change it so it doesn't include the ~/.ssh/ identities if you specify one with -i

**Comment by ryantm** [comment]
@nomeata Thanks for the report! I've fixed it in https://github.com/ryantm/agenix/pull/152

**Comment by nomeata** [comment]
Thanks!
