### ISSUE TITLE
Option to use minisign to verify secrets

### ISSUE THREAD

**Issue by cole-h** [ryantm/agenix#16]
As called out in https://github.com/ryantm/agenix#threat-modelwarnings, `age` does not (currently?) support authentication of secrets. However, if it were paired with [`minisign`](https://github.com/jedisct1/minisign), it may be possible to at least sidestep this limitation.

I imagine the API just being an additional 2 options: `minisignFile` and `verifySignature`. If `verifySignature` is true and `minisignFile` is unset, try `${file}.minisig`; if `verifySignature` is true and `minisignFile` is set, use that file; if `verifySignature` is false, don't verify.

Could also change `minisignFile` to `signatureFile` / `signaturePath`. This would allow extensibility if we ever want to implement support for a different signing program, and could just add a `signatureType` enum.

If the secret is validated, proceed. Otherwise, error loudly that the secret may have been tampered with. (Provide escape hatch to deploy / switch / whatever in spite of this?)

Thoughts? Would this be accepted as a PR?

EDIT: Of course, the signing key would need to be accessible; probably as another option.

**Comment by ryantm** [comment]
@cole-h I feel like the ergonomics of using agenix is already pretty bad, so I fear adding another key into the mix. What's your use case where you need authentication but cannot use say GPG signed got commits?

**Comment by cole-h** [comment]
To me, the whole point of using age(nix) is to get away from GPG, so that's the reason I wouldn't want to use GPG for signing. I understand the ergonomics concern, though. I'll still experiment with it for my own personal use, at least.

My use case is really just "prevent secrets from changing without my knowledge."

**Comment by cole-h** [comment]
I've tackled this in https://github.com/ryantm/agenix/pull/22. PTAL. It worked fine in my limited testing. I need to migrate from sops-nix to agenix now :P

**Comment by cole-h** [comment]
I recently read https://www.agwa.name/blog/post/ssh_signatures and realize that would be better (to me) than using minisign, so I'm going to close this. Maybe I'll be back with a PR using that functionality some day in the future.

**Comment by ryantm** [comment]
@cole-h yeah. I saw that to and agree. I think the path forward is to go all in on SSH identities. Really want to figure out how to support password protected SSH keys.
