### ISSUE TITLE
Workflow for new builds - General Help - Question

### ISSUE THREAD

**Issue by hurricanehrndz** [ryantm/agenix#17]
I am relatively new to nix, so I am having a hard time determining what the workflow would be for a new build. Meaning we do not know the public key of the host, for we have yet to build the system.

**Comment by ryantm** [comment]
Good question. Something about this should get added to the readme.

I think the best solution is to add the the secrets to the configuration after the machine is set up enough to have host SSH keys generated.

**Comment by hurricanehrndz** [comment]
Thank you so much for the clarification and all the great work.

**Comment by happysalada** [comment]
So if I understand correctly. The workflow would be
- setup a git repo with your nix configuration
- setup the machine to deploy to with nixos.
- Generate an ssh-key on the machine to deploy to
- Setup a git bare repo on the machine to deploy to
- Setup a git hook on the bare repo so that a push to the git bare repo will decrypt secrets and build your config (flake)

**Comment by ryantm** [comment]
No.

1. setup a git repo with your nix configuration
2. setup the machine to deploy to with NixOS
3. Use ssh-keyscan to get public ssh key of the machine you set up
4. Add that key to your git repo's `secrets.nix` file
5. Add the `age` module to your machine's nix configuration
6. Reploy nix configuration.

**Comment by happysalada** [comment]
Thank you for the correction!
I added things related to deploying the nix config, it makes sense to keep the workflow more general.

In 2. the setup includes generating a ssh key for the new machine you setup, or am I misunderstanding?

**Comment by ryantm** [comment]
When you setup a NixOS machine that uses ssh, when the ssh service starts, it generates a SSH keypair in the `/etc/ssh/` directory. You can access that public key remotely with `ssh-keyscan`.

**Comment by happysalada** [comment]
Thanks a lot!

**Comment by happysalada** [comment]
One additional question I have. The example in the readme only show a usecase for referencing a secret file. If there was to be a reference to a value. It would be something like the following?
```
       url =  "postgres://union_web:${builtins.readFile ./postgresPassword.age}@localhost:5432/db_name?sslmode=disable";
```

An additional naive question. Using readFile here, would that not put the secret in the nix store?

**Comment by ryantm** [comment]
No, because `builtins.readFile` cannot decrypt the file. Yes, that would put the cleartext in the nix store. It is pointless to use agenix in this case. 

I expect postgres supports a different connection method that makes use of a file.

**Comment by happysalada** [comment]
One more question.
On the host machine, the ssh-agent needs to be enabled right?
I have enable openssh with `services.openssh.enable = true;`
however 
```
|> ssh-add -l
Could not open a connection to your authentication agent.
```
I can see that
`sshd.service                           enabled         enabled`

should the setting `programs.ssh.startAgent = true;` be enabled?

Without the agent, on my local ssh-keyscan will return me the keys, but the host can't decrypt them.
I think i'm missing one tiny thing here.

**Comment by ryantm** [comment]
You shouldn't need ssh-agent, in fact rage/age don't work with it resulting in needing to type ssh key passwords manually. Ssh-keyscan returns a public key and public keys can't and do not need to be decrypted.

**Comment by happysalada** [comment]
Maybe I'm not using this right then.

Here is the contents of my secrets.nix
```
let
  raphael = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGyQSeQ0CV/qhZPre37+Nd0E9eW+soGs+up6a/bwggoP raphael@RAPHAELs-MacBook-Pro.local";
  hetzner-AX41 = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJXEqr5BHqxcOehdMvpM4sTqK388u3SDGo037ZKpNQfX root@hetzner-AX41-UEFI-ZFS-NVME";
in
{
  "unionBlue.env.age".publicKeys = [ raphael hetzner-AX41 ];
  "unionGreen.env.age".publicKeys = [ raphael hetzner-AX41 ];
}
```

Here is the content of the ssh public key
```
[root@hetzner-AX41-UEFI-ZFS-NVME:~/.ssh]# cat id_ed25519.pub
ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJXEqr5BHqxcOehdMvpM4sTqK388u3SDGo037ZKpNQfX root@hetzner-AX41-UEFI-ZFS-NVME
```

Here is the output of the decryption step
```
[root@hetzner-AX41-UEFI-ZFS-NVME:~/nixos-config/secrets]# agenix -e unionGreen.env.age -v
+ test 0 -gt 0
+ RULES=./secrets.nix
+ trap cleanup 0 2 3 15
+ '[' 0 -eq 1 ']'
+ edit unionGreen.env.age
+ FILE=unionGreen.env.age
++ nix-instantiate --eval -E '(let rules = import ./secrets.nix; in builtins.concatStringsSep "\n" rules."unionGreen.env.age".publicKeys)'
++ sed 's/"//g'
++ sed 's/\\n/\n/g'
+ KEYS='ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGyQSeQ0CV/qhZPre37+Nd0E9eW+soGs+up6a/bwggoP raphael@RAPHAELs-MacBook-Pro.local
ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJXEqr5BHqxcOehdMvpM4sTqK388u3SDGo037ZKpNQfX root@hetzner-AX41-UEFI-ZFS-NVME'
+ '[' -z 'ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGyQSeQ0CV/qhZPre37+Nd0E9eW+soGs+up6a/bwggoP raphael@RAPHAELs-MacBook-Pro.local
ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJXEqr5BHqxcOehdMvpM4sTqK388u3SDGo037ZKpNQfX root@hetzner-AX41-UEFI-ZFS-NVME' ']'
++ mktemp -d
+ CLEARTEXT_DIR=/tmp/tmp.C9SLDfCtEo
++ basename unionGreen.env.age
+ CLEARTEXT_FILE=/tmp/tmp.C9SLDfCtEo/unionGreen.env.age
+ '[' -f unionGreen.env.age ']'
+ DECRYPT=("${DEFAULT_DECRYPT[@]}")
+ '[' -f /root/.ssh/id_rsa ']'
+ '[' -f /root/.ssh/id_ed25519 ']'
+ DECRYPT+=(--identity "$HOME/.ssh/id_ed25519")
+ [[ --decrypt --identity /root/.ssh/id_ed25519 != *\-\-\i\d\e\n\t\i\t\y* ]]
+ DECRYPT+=(-o "$CLEARTEXT_FILE" "$FILE")
+ /nix/store/ldgnyyv8a3qvv7glyi8qany20xbbzh5a-rage-0.5.0/bin/rage --decrypt --identity /root/.ssh/id_ed25519 -o /tmp/tmp.C9SLDfCtEo/unionGreen.env.age unionGreen.env.age
Error: No matching keys found

[ Did rage not do what you expected? Could an error be more useful? ]
[ Tell us: https://str4d.xyz/rage/report                            ]
+ exit 1
+ cleanup
+ '[' '!' -z x ']'
+ rm -rf /tmp/tmp.C9SLDfCtEo
+ '[' '!' -z ']'
```

To be sure, I edited the file again to make sure it was encrypted.

trying to rekey gives me the following error
```
❯ agenix --rekey
rekeying unionBlue.env.agenunionGreen.env.age...
error: attribute 'unionBlue.env.agenunionGreen.env.age' missing

       at «string»:1:70:

            1| (let rules = import ./secrets.nix; in builtins.concatStringsSep "\n" rules."unionBlue.env.agenunionGreen.env.age".publicKeys)
             |                                                                      ^
There is no rule for unionBlue.env.agenunionGreen.env.age in ./secrets.nix
```
It looks like it's trying to concatenate both filenames.

**Comment by ryantm** [comment]
@happysalada You are doing something atypical in that you are using the ssh key of the root user on your server. The typical use case is to use the the host ssh key in `/etc/ssh/`.

When it says "no matching keys found", that probably just means your secret is not keyed to the root user's public SSH key.

I don't quite understand what is going on with your rekey attempt, but I tried copying your secrets.nix file to my computer and then:
```ShellSession
$ nix run github:ryantm/agenix -- --rekey
rekeying unionBlue.env.age...
unionBlue.env.age wasn't created.
rekeying unionGreen.env.age...
unionGreen.env.age wasn't created.
```

Could you post the console session output of these commands?
```
cat secrets.nix
agenix --help
agenix -v --rekey
```

**Comment by happysalada** [comment]
I forgot to mention, I just copied the host keys into the .ssh directory and switched their names at some point, just because I noticed that the default identity variable is to linked to .ssh/id_ed25519
Those are the host keys, they can also be found at `/etc/ssh/ssh_host_ed25519` and also the pub key.
I'm sorry I don't understand the sentence 
```
When it says "no matching keys found", that probably just means your secret is not keyed to the root user's public SSH key.
```
How do I key it?

Here is the output of the commands
```
❯ cat secrets.nix
let
  raphael = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGyQSeQ0CV/qhZPre37+Nd0E9eW+soGs+up6a/bwggoP raphael@RAPHAELs-MacBook-Pro.local";
  hetzner-AX41 = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJXEqr5BHqxcOehdMvpM4sTqK388u3SDGo037ZKpNQfX root@hetzner-AX41-UEFI-ZFS-NVME";
in
{
  "unionBlue.env.age".publicKeys = [ raphael hetzner-AX41 ];
  "unionGreen.env.age".publicKeys = [ raphael hetzner-AX41 ];
}
```

```
❯ agenix --help
agenix - edit and rekey age secret files

agenix -e FILE [-i PRIVATE_KEY]
agenix -r [-i PRIVATE_KEY]

options:
-h, --help                show help
-e, --edit FILE           edits FILE using $EDITOR
-r, --rekey               re-encrypts all secrets with specified recipients
-i, --identity            identity to use when decrypting
-v, --verbose             verbose output

FILE an age-encrypted file

PRIVATE_KEY a path to a private SSH key used to decrypt file

EDITOR environment variable of editor to use when editing FILE

RULES environment variable with path to Nix file specifying recipient public keys.
Defaults to './secrets.nix'

age binary path: /nix/store/68i3vfqgsqy0v8csaikdgv7f52xwrh52-rage-0.5.0/bin/rage
age version: rage 0.5.0
```

```
❯ agenix -v --rekey
+ test 1 -gt 0
+ case "$1" in
+ shift
+ REKEY=1
+ test 0 -gt 0
+ RULES=./secrets.nix
+ trap cleanup 0 2 3 15
+ '[' 1 -eq 1 ']'
+ rekey
++ nix-instantiate --eval -E '(let rules = import ./secrets.nix; in builtins.concatStringsSep "\n" (builtins.attrNames rules))'
++ sed 's/"//g'
++ sed 's/\\n/\n/g'
+ FILES=unionBlue.env.agenunionGreen.env.age
+ for FILE in $FILES
+ echo 'rekeying unionBlue.env.agenunionGreen.env.age...'
rekeying unionBlue.env.agenunionGreen.env.age...
+ EDITOR=:
+ edit unionBlue.env.agenunionGreen.env.age
+ FILE=unionBlue.env.agenunionGreen.env.age
++ nix-instantiate --eval -E '(let rules = import ./secrets.nix; in builtins.concatStringsSep "\n" rules."unionBlue.env.agenunionGreen.env.age".publicKeys)'
++ sed 's/"//g'
++ sed 's/\\n/\n/g'
error: attribute 'unionBlue.env.agenunionGreen.env.age' missing

       at «string»:1:70:

            1| (let rules = import ./secrets.nix; in builtins.concatStringsSep "\n" rules."unionBlue.env.agenunionGreen.env.age".publicKeys)
             |                                                                      ^
++ exit 1
+ KEYS=
+ '[' -z '' ']'
+ echo 'There is no rule for unionBlue.env.agenunionGreen.env.age in ./secrets.nix.'
There is no rule for unionBlue.env.agenunionGreen.env.age in ./secrets.nix.
+ exit 1
+ cleanup
+ '[' '!' -z ']'
+ '[' '!' -z ']'
```

```
❯ readlink (which agenix)
/nix/store/bvswi9pk1978cpwykrxknppjxs0nppxr-home-manager-path/bin/agenix
```
(adapted since I use fish)

```
❯ cat (which agenix)
#!/nix/store/v2s6gfd99q8hl2l1ysc56158ry1csjas-bash-4.4-p23/bin/bash
set -Eeuo pipefail

PACKAGE="agenix"

function show_help () {
  echo "$PACKAGE - edit and rekey age secret files"
  echo " "
  echo "$PACKAGE -e FILE [-i PRIVATE_KEY]"
  echo "$PACKAGE -r [-i PRIVATE_KEY]"
  echo ' '
  echo 'options:'
  echo '-h, --help                show help'
  echo '-e, --edit FILE           edits FILE using $EDITOR'
  echo '-r, --rekey               re-encrypts all secrets with specified recipients'
  echo '-i, --identity            identity to use when decrypting'
  echo '-v, --verbose             verbose output'
  echo ' '
  echo 'FILE an age-encrypted file'
  echo ' '
  echo 'PRIVATE_KEY a path to a private SSH key used to decrypt file'
  echo ' '
  echo 'EDITOR environment variable of editor to use when editing FILE'
  echo ' '
  echo 'RULES environment variable with path to Nix file specifying recipient public keys.'
  echo "Defaults to './secrets.nix'"
  echo ' '
  echo "age binary path: /nix/store/68i3vfqgsqy0v8csaikdgv7f52xwrh52-rage-0.5.0/bin/rage"
  echo "age version: $(/nix/store/68i3vfqgsqy0v8csaikdgv7f52xwrh52-rage-0.5.0/bin/rage --version)"
}

test $# -eq 0 && (show_help && exit 1)

REKEY=0
DEFAULT_DECRYPT=(--decrypt)

while test $# -gt 0; do
  case "$1" in
    -h|--help)
      show_help
      exit 0
      ;;
    -e|--edit)
      shift
      if test $# -gt 0; then
        export FILE=$1
      else
        echo "no FILE specified"
        exit 1
      fi
      shift
      ;;
    -i|--identity)
      shift
      if test $# -gt 0; then
        DEFAULT_DECRYPT+=(--identity "$1")
      else
        echo "no PRIVATE_KEY specified"
        exit 1
      fi
      shift
      ;;
    -r|--rekey)
      shift
      REKEY=1
      ;;
    -v|--verbose)
      shift
      set -x
      ;;
    *)
      show_help
      exit 1
      ;;
  esac
done

RULES=${RULES:-./secrets.nix}

function cleanup {
    if [ ! -z ${CLEARTEXT_DIR+x} ]
    then
        rm -rf "$CLEARTEXT_DIR"
    fi
    if [ ! -z ${REENCRYPTED_DIR+x} ]
    then
        rm -rf "$REENCRYPTED_DIR"
    fi
}
trap "cleanup" 0 2 3 15

function edit {
    FILE=$1
    KEYS=$((nix-instantiate --eval -E "(let rules = import $RULES; in builtins.concatStringsSep \"\n\" rules.\"$FILE\".publicKeys)" | sed 's/"//g' | sed 's/\\n/\n/g') || exit 1)

    if [ -z "$KEYS" ]
    then
        >&2 echo "There is no rule for $FILE in $RULES."
        exit 1
    fi

    CLEARTEXT_DIR=$(mktemp -d)
    CLEARTEXT_FILE="$CLEARTEXT_DIR/$(basename "$FILE")"

    if [ -f "$FILE" ]
    then
        DECRYPT=("${DEFAULT_DECRYPT[@]}")
        if [ -f "$HOME/.ssh/id_rsa" ]; then
            DECRYPT+=(--identity "$HOME/.ssh/id_rsa")
        fi
        if [ -f "$HOME/.ssh/id_ed25519" ]; then
            DECRYPT+=(--identity "$HOME/.ssh/id_ed25519")
        fi
        if [[ "${DECRYPT[*]}" != *"--identity"* ]]; then
          echo "No identity found to decrypt $FILE. Try adding an SSH key at $HOME/.ssh/id_rsa or $HOME/.ssh/id_ed25519 or using the --identity flag to specify a file."
          exit 1
        fi
        DECRYPT+=(-o "$CLEARTEXT_FILE" "$FILE")
        /nix/store/68i3vfqgsqy0v8csaikdgv7f52xwrh52-rage-0.5.0/bin/rage "${DECRYPT[@]}" || exit 1
        cp "$CLEARTEXT_FILE" "$CLEARTEXT_FILE.before"
    fi

    $EDITOR "$CLEARTEXT_FILE"

    if [ ! -f "$CLEARTEXT_FILE" ]
    then
      echo "$FILE wasn't created."
      return
    fi
    [ -f "$FILE" ] && [ "$EDITOR" != ":" ] && diff "$CLEARTEXT_FILE.before" "$CLEARTEXT_FILE" 1>/dev/null && echo "$FILE wasn't changed, skipping re-encryption." && return

    ENCRYPT=()
    while IFS= read -r key
    do
        ENCRYPT+=(--recipient "$key")
    done <<< "$KEYS"

    REENCRYPTED_DIR=$(mktemp -d)
    REENCRYPTED_FILE="$REENCRYPTED_DIR/$(basename "$FILE")"

    ENCRYPT+=(-o "$REENCRYPTED_FILE")

    /nix/store/68i3vfqgsqy0v8csaikdgv7f52xwrh52-rage-0.5.0/bin/rage "${ENCRYPT[@]}" <"$CLEARTEXT_FILE" || exit 1

    mv -f "$REENCRYPTED_FILE" "$1"
}

function rekey {
    FILES=$((nix-instantiate --eval -E "(let rules = import $RULES; in builtins.concatStringsSep \"\n\" (builtins.attrNames rules))"  | sed 's/"//g' | sed 's/\\n/\n/g') || exit 1)

    for FILE in $FILES
    do
        echo "rekeying $FILE..."
        EDITOR=: edit "$FILE"
        cleanup
    done
}

[ $REKEY -eq 1 ] && rekey && exit 0
edit "$FILE" && cleanup && exit 0
```

**Comment by happysalada** [comment]
I have a separate question regarding usage of agenix with systemd services.
With systemd, there are 3 ways to pass environment variables.
- Directly defining something like `environment.MY_VAR = "MYVALUE;`
- passing an environment file like `serviceConfig.EnvironmentFile = ./my_path.env;`
- The doc talks about a LoadCredential and SetCredential https://man7.org/linux/man-pages/man5/systemd.exec.5.html

The official doc discourages passing secrets with environment or EnvironmentFile and encourages to use LoadCredential. LoadCredential expects something in the form of `ID[:PATH]`. It can't work with nix right? In order for this to work, the path would have to be added to the nix store and then it would become world readable, right?

I just want to confirm that the only way to use agenix with systemd is through the `EnvironmentFile` option.

**Comment by ryantm** [comment]
@happysalada sorry for the slow reply.

Something is working differently on your system for this line than on my system:
```
    FILES=$((nix-instantiate --eval -E "(let rules = import $RULES; in builtins.concatStringsSep \"\n\" (builtins.attrNames rules))"  | sed 's/"//g' | sed 's/\\n/\n/g') || exit 1)
```
It might help to separate out the pipe outputs to see what:

```
[ryantm@home1:~/p/agenix]$ ONE=$(nix-instantiate --eval -E "(let rules = import ./secrets.nix; in builtins.concatStringsSep \"\n\" (builtins.attrNames rules))")

[ryantm@home1:~/p/agenix]$ echo $ONE
"unionBlue.env.age\nunionGreen.env.age"

[ryantm@home1:~/p/agenix]$ echo $ONE | sed 's/"//g'
unionBlue.env.age\nunionGreen.env.age

[ryantm@home1:~/p/agenix]$ echo $ONE | sed 's/"//g' | sed 's/\\n/\n/g'
unionBlue.env.age
unionGreen.env.age
```

**Comment by happysalada** [comment]
I'm really grateful that you are taking the time to answer and debug this! So feel free to answer at your own pace, no problem with me!

I use fish shell, so I had to do a little bit of replacement
```
set ONE (nix-instantiate --eval -E "(let rules = import ./secrets.nix; in builtins.concatStringsSep \"\n\" (builtins.attrNames rules))")
❯ echo $ONE
"unionBlue.env.age\nunionGreen.env.age"
❯ echo $ONE | sed 's/"//g' | sed 's/\\n/\n/g'
unionBlue.env.age\nunionGreen.env.age
```
It looks like the second sed isn't doing what you expect it to do. I'm on OSX that might be why.

**Comment by ryantm** [comment]
The fish shell changes shouldn't be relevant since it will be running in bash. I've not used MacOS in years, but I hear that maybe the line endings are different, so that could explain it maybe. Could you play around with the sed command to see if you can fix it? If you can, I'll try it on NixOS and maybe we can fix agenix to work on both platforms.

**Comment by happysalada** [comment]
I found a weird answer

```
❯ echo $ONE | sed 's/"//g' | sed 's/\\\n/\
  /g'
```

coming from 
https://stackoverflow.com/questions/46082397/insert-newline-n-using-sed
The portable way to get a newline in sed is a backslash followed by a literal newline

Let me know if that works for you

**Comment by asymmetric** [comment]
Shouldn't we be running gnused on macOS too?

**Comment by happysalada** [comment]
Running GNU sed, could be another way to fix this.
I just tried and it works on my machine.
The fix is as simple as replacing `sed` with `${pkgs.gnused}/bin/sed`.
Let me know if you want me to make a PR.

**Comment by ryantm** [comment]
Yeah, I'd prefer to fix it that way.

**Comment by ryantm** [comment]
@asymmetric @happysalada Made the fix the way I prefer at https://github.com/ryantm/agenix/pull/37 please check it out.

**Comment by happysalada** [comment]
Thank you so much for fixing the first issue.

Here is the second issue for me.
I have checked that I am able to edit the secret file on the host.
I have to use the command `agenix -i /etc/ssh/ssh_host_ed25519_key -e unionBlue.env.age` specifying the host ssh key.
I have specified that file as the EnvironmentFile for one of my systemd services.
I know that the file is not being decrypted properly because i have a failure in the systemd service with the message
```
union-blue.service: Failed to load environment files: Bad message
```
If I load the environment file not encrypted i don't have a problem.
I don't know how to debug the issue though.
I have also verified that I was running agenix from the master of today with the latest sed issue fixed.
I'm open to try anything here.

**Comment by happysalada** [comment]
Ok, I realise my mistake now. I didn't understand the usage at all.

For a secret, it should go under the top level attribute, `age.secrets`. For my environment file the solution was
```
  age.secrets.unionBlueEnv = {
    name = "unionBlueEnv";
    file = ./secrets/unionBlue.env.age;
  };
```
then to reference it, it should be
`environmentFile = "/run/secrets/unionBlueEnv";`

I will try to re-read the documentation and propose something.
I see there is already a PR to add to the doc.

**Comment by happysalada** [comment]
There was one more thing I thought could be a good addition.
Giving an example of a potential use case.
Something like showing a systemd with LoadCredential option. It seems it's the recommended way to use secrets with systemd.
I realise that this might be out of scope, so feel free to ignore it if you don't think it's relevant.
