### ISSUE TITLE
TODO: add README with threat-model

### ISSUE THREAD

**Issue by Mic92** [ryantm/agenix#2]
People unfamiliar with age might be surprised that secrets are not authenticated.
This means that every `attacker` that has write access to the repository can modify secrets because public keys are exposed.
This seems not a problem on the first glance because changing configuration itself could
expose secrets easily. However it is easier to review configuration changes rather than random secrets i.e. 4096-bit rsa keys.
This would be solved by having a message authentication code (MAC) like other implementations like gpg or sops have, however this was left out for simplicity in age.

**Comment by ryantm** [comment]
Added README with basically this paragraph in it. Thanks!
