### ISSUE TITLE
Is there any way to "post-process" a secret?

### ISSUE THREAD

**Issue by charmoniumQ** [ryantm/agenix#200]
This issue is easiest to explain in an example: Vaultwarden and Nextcloud both need to be able to log in to an SMTP server in order to send mail on their behalf. I pay for email service per use, so I'd like to use one login for both. However, the NixOS Vaultwarden module needs the password in a file like `SMTP_PASSWORD=${password goes here` ([docs](https://nixos.org/manual/nixos/unstable/options#opt-services.vaultwarden.environmentFile)), whereas the NixOS Nextcloud module needs the password in a file like `{"mail_smtppassword": "${password goes here}"}`.

Is there a way I can store the password once in agenix and post-process it two ways? Otherwise, would I have to painstakingly override those NixOS modules? Is there another way I am not seeing?

**Comment by charmoniumQ** [comment]
I ended up writing some hacky activation scripts to do this, but I am still wondering if there is a better way.

**Comment by stephank** [comment]
I think activation scripts are the way. I ended up doing something like:

```nix
{ config, lib, ... }:

lib.mkIf (config.age.secrets != { }) {

  system.activationScripts.agenixCustom = lib.stringAfter "agenixChown" ''
    # Your extension here.
  '';

  # So scripts that depend on "agenix" also depend on the extension.
  system.activationScripts.agenix.deps = [ "agenixCustom" ];

}
```

**Comment by charmoniumQ** [comment]
That's a good idea
