### ISSUE TITLE
jq compile error during newline removal

### ISSUE THREAD

**Issue by gmemstr** [ryantm/agenix#207]
It seems that https://github.com/ryantm/agenix/commit/b5fa96a90e07cc099cc5247540449263caeedb16 introduced a regression in editing secrets. When editing any secret, the following error is produced:

```
jq: error: syntax error, unexpected '[', expecting FORMAT or QQSTRING_START (Unix shell quoting issues?) at <top-level>, line 1:
map(rtrimstr("\n")) .[]                     
jq: 1 compile error
```

Maybe some extra escaping is required around the rtrimstr?

**Comment by ryantm** [comment]
Reverted that for now. Thanks for the report.
