### ISSUE TITLE
Removing old secrets

### ISSUE THREAD

**Issue by asymmetric** [ryantm/agenix#21]
I noticed that the current logic, which relies on `activationScripts`, leaves old secrets around.

E.g., if I rename a secret in my `secrets.nix`, the new and the old secret will both be present on the machine.

Have you considered using systemd oneshot units? AFAICT, those are garbage-collected [on system switch](https://github.com/NixOS/nixpkgs/blob/8c8731330b53ba0061686f36f10f101e662a4717/nixos/modules/system/activation/switch-to-configuration.pl#L144-L151).

**Comment by ryantm** [comment]
The default place the secrets are stored is `/run`, so they'll be removed eventually.

I haven't considered using systemd oneshot units yet. Can they be installed and run before the `activationScripts`? I want to be able to store hashed Linux user passwords in agenix, and this requires making sure the secrets are in place before the NixOS user activation script runs.

**Comment by ryantm** [comment]
Will be addressed by #26
