### ISSUE TITLE
`age.identityPaths` still up to date?

### ISSUE THREAD

**Issue by TornaxO7** [ryantm/agenix#218]
Hi!
The section about [age.identityPaths](https://github.com/ryantm/agenix#ageidentitypaths) says:
> (...) The list items should be strings ("/path/to/id_rsa"), not nix paths (../path/to/id_rsa), as the latter would copy your private key to the nix store, which is the exact situation agenix is designed to avoid. (...)

but I'm getting the following error message with:
```nix
    age.identityPaths = [ "test" ];
```
```nix
error:
       … while checking flake output 'nixosConfigurations'

         at /nix/store/74dsgrd4mw8vzwsria2zvcpd1l5cirxd-source/flake.nix:45:7:

           44|     {
           45|       nixosConfigurations = {
             |       ^
           46|         pc = init_system {

       … while checking the NixOS configuration 'nixosConfigurations.pc'

         at /nix/store/74dsgrd4mw8vzwsria2zvcpd1l5cirxd-source/flake.nix:46:9:

           45|       nixosConfigurations = {
           46|         pc = init_system {
             |         ^
           47|           configuration = ./nixos-configurations/pc/default.nix;

       (stack trace truncated; use '--show-trace' to show the full trace)

       error: A definition for option `age.identityPaths."[definition 1-entry 1]"' is not of type `path'. Definition values:
       - In `/nix/store/74dsgrd4mw8vzwsria2zvcpd1l5cirxd-source/secrets/default.nix': "test"
```

**Comment by TornaxO7** [comment]
hm... but does that mean that I have to use absolute paths?

**Comment by ambroisie** [comment]
Well yes, otherwise what are your paths relative _to_?

**Comment by TornaxO7** [comment]
hm... ok, maybe I can create an absolute with the help of `self`

**Comment by Endermanbugzjfc** [comment]
https://github.com/ryantm/agenix/blob/b027ee29d959fda4b60b57566d64c98a202e0feb/README.md?plain=1#L403

It has been 2 years or so. This line is still outdated.
