### ISSUE TITLE
Darwin: Undefined variable `Foundation` 

### ISSUE THREAD

**Issue by felixscheinost** [ryantm/agenix#24]
Hi! 

I recently added `Foundation` to the `buildInputs` on darwin. (PR #20)

But unfortunately PR #19 broke support on my machine again. 

The build complains about a missing attribute `pkgs.darwin.Foundation` while `pkgs.darwin.apple_sdk.frameworks.Foundation` does work for me.

My PR added `darwin.apple_sdk.frameworks.Foundation` while the other PR changed it to `darwin.Foundation`.

I am not sure if this is the result of merge gone wrong or whether somethings wrong with my setup.

Thanks!
Felix

**Comment by ryantm** [comment]
@felixscheinost Thanks for the report. I changed it to your way since I see that in nixpkgs all-packages.nix. Could you check if it is working now on master?

**Comment by felixscheinost** [comment]
Thanks! Its working now on a704a85cbdceb5b6da2c29767dd7a1f446fde7a6.
