### ISSUE TITLE
[ERROR i18n_embed::requester] Unable to parse your locale: ParseError(InvalidLanguage)

### ISSUE THREAD

**Issue by voobscout** [ryantm/agenix#25]
Encountered on 20.09, resulting in secrets not being decrypted.
```shell
dmesg | grep stage-2-
# [ERROR i18n_embed::requester] Unable to parse your locale: ParseError(InvalidLanguage)
```
The fix is:
```nix
{config, pkgs, lib, ...}:
{
  system.activationScripts.agenixFixLocale = lib.stringAfter [ "stdio" ] ''
    export LANG=${config.i18n.defaultLocale} \
           LOCALE_ARCHIVE=${config.i18n.glibcLocales}/lib/locale/locale-archive
  '';
}
```

Likely, locale should be set for stage-2 in [here](https://github.com/NixOS/nixpkgs/blob/2394284537b89471c87065b040d3dedd8b5907fe/nixos/modules/system/activation/activation-script.nix#L84), since other things might depend on it as well, but having experienced no side-effects without agenix, can't be certain. Maybe it's just a rust thing, no idea.

**Comment by ryantm** [comment]
@voobscout Thanks for the report. I merged #28 which should resolve this, but please let me know if it doesn't!
