### ISSUE TITLE
Understanding secrets workflow

### ISSUE THREAD

**Issue by pimeys** [ryantm/agenix#29]
Hi. I'm currently converting my systems into nixos, and going with the flakes design already. I'm almost there, but I have a thing with agenix I cannot seem to get working.

I have a few things in my setup I do not want to push to the git repo. Secrets, that can easily stay unencrypted in my computer's memory, but that might not be such a great idea to push to the github.

So I have a nix file with my secrets, but what I can get from agenix is only the path to the unencrypted file, not the file content itself. Now let's say I have a file `home.age`, that has encrypted the following nix script:

```nix
{
  key = "secret";
}
```
Now, I'd import the data in my configuration with:
```nix
let
  home-secrets = import "${config.age.secrets.home.path}";
in {
  ...
}
```
But, this is not possible, and will lead to an error:
```
❯ sudo nixos-rebuild switch
warning: Git tree '/home/pimeys/.config/nixpkgs' is dirty
building the system configuration...
warning: Git tree '/home/pimeys/.config/nixpkgs' is dirty
error: --- RestrictedPathError ----------------------------------------------------------------------- nix
access to path '/run/secrets/home' is forbidden in restricted mode
(use '--show-trace' to show detailed location information)
```
I'm asking, is this even possible with agenix and flakes? What I want is to get the data out from the secrets, set them to system env vars and use them when my system boots up. If agenix is not the right tool for this, is there another way I could utilize a few tokens in nixos without needing to push them to a git repository?

**Comment by ryantm** [comment]
The flakes system is stopping you from doing something you probably don't intend: you are trying to feedback the deployed configuration into the configuration.

* If you are trying to reference the file path in your configuration, you wouldn't import it.
* When using flakes, all the files you depend on need to be part of the source repository, so you wouldn't be able to import the cleartext file in your configuration like that.

It should be possible to configure part of your system to set environment variables by reading a file at boot time. I'm not super familiar with how to do that though.

**Comment by pimeys** [comment]
The problem with the last approach is that the secret file is deleted on reboot, which makes doing stuff like shell scripting in the file and sourcing it during boot impossible.

**Comment by ryantm** [comment]
If you want to do that you wouldn't use agenix, just place the cleartext wherever you want to load it from.

**Comment by pimeys** [comment]
Thank you for pointing me to the simple solution. Having a submodule from a private repo at home in my nixconfig and sourcing it on boot worked miracles.
