### ISSUE TITLE
Error: Header is invalid

### ISSUE THREAD

**Issue by winston0410** [ryantm/agenix#63]
I got this error but I have no idea how to resolve. I have a `secrets.nix` like this:

```nix
let
  macbook2017 =
    "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIESRdLYXkaqruy2cq7LFiwuYpkz+BIEGoaDz5pl58o+5 hugosum.dev@protonmail.com";
in { "telegram-bot.age".publicKeys = [ macbook2017 ]; }

```

And I run it like this:

```
touch telegram-bot.age
nix run github:ryantm/agenix -- -e telegram-bot.age
```

And I got this:

```
warning: unknown setting 'experimental-features'
Error: Header is invalid

[ Did rage not do what you expected? Could an error be more useful? ]
[ Tell us: https://str4d.xyz/rage/report                            ]
```

Is this an upstream issue?

**Comment by ryantm** [comment]
I don't think it is a good idea to document all the things you should not do, the documentation will get to large doing this. If there is some way to make it more clear though, I'm all for a pull request for that!
