### ISSUE TITLE
Restrict folder permissions

### ISSUE THREAD

**Issue by pinpox** [ryantm/agenix#68]
Hello, I'm trying out agenix as a replacement for my current secret management scheme (krops + pass). Is there a reason why the `/run/secrets/` directory has so open permissions of `755`? I don't think others should be able to list the directory at all.

I think it would provide additional security at virtually no cost to set it to something like `0751` like sops-nix does or even to `440` so that only root can read them. If changing this in general is a problem, it would be nice to at least have the option to change them myself.

**Comment by ryantm** [comment]
@pinpox the latest version of agenix does not use `/run/secrets/` at all. Maybe you are using an old version?
