### ISSUE TITLE
Plain text of <number>+<keyword> in an agenix encrypted secret?

### ISSUE THREAD

**Issue by nixinator** [ryantm/agenix#99]
`-> 8-grease bfk YcfjhO d(I"`

this plaintext appears in .age files, I'm just curious what it is. You get new numbers and keywords when encrypting with agenix.

Utterly brilliant piece of software...

All we need now all API developers and platforms to provide agenix secrets too, I can the just simply fetch them with curl! :-)

**Comment by ryantm** [comment]
Those files are .age encrypted files. You can look at https://github.com/FiloSottile/age/ for more details. Or the [format specification](https://docs.google.com/document/d/11yHom20CrsuX8KQJXBBw04s80Unjv8zCg_A7sPAX_9Y/preview).
